# Uncomment the next line to define a global platform for your project
platform :ios, '17.2'

target 'runo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for runo
  pod 'KeychainAccess'

  target 'runoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'runoUITests' do
    # Pods for testing
  end

end
